# Generated by Django 5.2.7 on 2026-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2_turbo_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='steam_friends',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='steamuser',
            name='steam_friends_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
