# Generated by Django 5.2.7 on 2025-12-13 18:15

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.IntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image_url', models.URLField()),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'indexes': [models.Index(fields=['name'], name='dota2_turbo_name_8fbd98_idx'), django.contrib.postgres.indexes.GinIndex(fields=['positions'], name='dota2_turbo_positio_00033d_gin')],
            },
        ),
        migrations.CreateModel(
            name='HeroFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet_id', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('gradient_id', models.IntegerField(default=0)),
                ('winrate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pickrate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tier', models.CharField(default='NR', max_length=2)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='dota2_turbo_hero.hero')),
            ],
            options={
                'verbose_name': 'HeroFacet',
                'verbose_name_plural': 'HeroFacets',
                'indexes': [models.Index(fields=['hero'], name='dota2_turbo_hero_id_649abc_idx'), models.Index(fields=['tier'], name='dota2_turbo_tier_1278d2_idx')],
                'unique_together': {('hero', 'facet_id')},
            },
        ),
        migrations.CreateModel(
            name='HeroTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=2)),
                ('winrate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pickrate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('period', models.CharField(choices=[('month', 'Last 30 days'), ('3months', 'Last 90 days'), ('6months', 'Last 180 days')], default='6months', max_length=20)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='dota2_turbo_hero.hero')),
            ],
            options={
                'verbose_name': 'HeroTier',
                'verbose_name_plural': 'HeroTiers',
                'indexes': [models.Index(fields=['period'], name='dota2_turbo_period_24e38b_idx'), models.Index(fields=['hero'], name='dota2_turbo_hero_id_9cf931_idx'), models.Index(fields=['tier'], name='dota2_turbo_tier_6a1ceb_idx')],
                'unique_together': {('hero', 'period')},
            },
        ),
    ]
