# Generated by Django 5.2.7 on 2026-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2_turbo_hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herotier',
            name='period',
            field=models.CharField(choices=[('week', 'Last 7 days'), ('month', 'Last 30 days'), ('3months', 'Last 90 days'), ('6months', 'Last 180 days')], default='6months', max_length=20),
        ),
    ]
