# Generated by Django 5.2.7 on 2025-12-13 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dota2_turbo_hero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('win', models.BooleanField()),
                ('rating_change', models.IntegerField()),
                ('match_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='dota2_turbo_hero.hero')),
                ('hero_facet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='dota2_turbo_hero.herofacet')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'indexes': [models.Index(fields=['player', 'match_id'], name='dota2_turbo_player__a025e7_idx')],
                'unique_together': {('match_id', 'player')},
            },
        ),
    ]
