# Generated by Django 5.2.7 on 2025-12-25 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dota2_turbo_hero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHeroStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_played', models.DateTimeField()),
                ('games', models.IntegerField()),
                ('win', models.IntegerField()),
                ('with_games', models.IntegerField()),
                ('with_win', models.IntegerField()),
                ('against_games', models.IntegerField()),
                ('against_win', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_heroes_stats', to='dota2_turbo_hero.hero')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_heroes_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlayerHeroStats',
                'verbose_name_plural': 'PlayerHeroStats',
                'ordering': ['-hero_id'],
                'unique_together': {('player', 'hero_id')},
            },
        ),
    ]
