# Generated by Django 5.2.7 on 2025-12-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2_turbo_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerherostats',
            name='against_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerherostats',
            name='against_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerherostats',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerherostats',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerherostats',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerherostats',
            name='with_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerherostats',
            name='with_win',
            field=models.IntegerField(default=0),
        ),
    ]
